"""add verification and source fields to properties

Revision ID: 48e7203af5b0
Revises: 7d80be9b35b5
Create Date: 2026-08-27 22:04:59.618740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e7203af5b0'
down_revision: Union[str, Sequence[str], None] = '7d80be9b35b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('source', sa.String(), server_default='manual', nullable=False))
    op.add_column('properties', sa.Column('verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('properties', sa.Column('verification_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('properties', sa.Column('outdated_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('properties', sa.Column('last_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'last_verified_at')
    op.drop_column('properties', 'outdated_count')
    op.drop_column('properties', 'verification_count')
    op.drop_column('properties', 'verified')
    op.drop_column('properties', 'source')
    op.drop_column('properties', 'source_url')
    # ### end Alembic commands ###
