# app/schemas/property.py
#
# PURPOSE: Defines Pydantic schemas for the Property resource.
# These schemas control what data the API accepts (input) and returns (output).
#
# PATTERN: DTO (Data Transfer Object) — schemas carry data between the HTTP layer
# and the service layer without exposing the internal SQLAlchemy model directly.
#
# WHY SEPARATE FROM THE MODEL:
# The SQLAlchemy model (models/property.py) defines the database structure.
# These schemas define the API contract. They are intentionally different —
# you may store more in the DB than you expose in the API, and vice versa.
#
# Pydantic validates all data automatically — if a request sends the wrong type
# or missing required fields, FastAPI returns a 422 error before your code runs.

from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime
from typing import Optional
from decimal import Decimal

# PropertyBase contains all fields shared between creating and reading a property.
# It acts as the foundation — other schemas inherit from it to avoid repetition.

class PropertyBase(BaseModel):

    # title — required, max 255 chars matches the DB column constraint
    # Field() lets us add validation rules and documentation
    title: str = Field(..., max_length=255,description="Property listing title", example="Cozy 2-bedroom apartment in downtown") 

    # description — optional, no max length (TEXT in DB)
    description: Optional[str] = Field(None, description="Detailed description of the property", example="This spacious apartment features hardwood floors, a modern kitchen, and a balcony with city views.")

    # price — Decimal matches the Numeric(12,2) DB column
    # gt=0 means price must be greater than 0 — no free or negative properties
    price: Decimal = Field(..., gt=0, description="Rental price per month", example=1500.00)

    # address — required, full street address
    address: str = Field(..., min_length=1, max_length=500, description="Full street address")

    # city — required, used for filtering on the map
    city: str = Field(..., min_length=1, max_length=100, description="City name")

    # latitude and longitude — required for MapLibre map markers
    # ge/le constraints enforce valid coordinate ranges globally
    latitude: float = Field(..., ge=-90, le=90, description="Latitude coordinate for map pin")
    longitude: float = Field(..., ge=-180, le=180, description="Longitude coordinate for map pin")

    # property_type — e.g. "apartment", "house", "land", "commercial"
    property_type: str = Field(..., min_length=1, max_length=50, description="Type of property")

    # status — e.g. "for_sale", "for_rent", "sold", "rented"
    status: str = Field(..., min_length=1, max_length=50, description="Current listing status")



#PropertyCreate is used when a client sends a POST request to create a property.
# It inherits all fields from PropertyBase with no additions needed right now.
# Having it as a separate class means we can add create-specific fields later
# (e.g. owner_id when authentication is added) without touching other schemas.
class PropertyCreate(PropertyBase):
    pass


# PropertyResponse is what the API returns when reading property data.
# It adds fields that only exist after the record is saved to the database —
# id, created_at, updated_at are generated by PostgreSQL, not sent by the client.
class PropertyResponse(PropertyBase):
    id: int
    created_at: datetime
    updated_at: datetime

    # model_config tells Pydantic to read data from SQLAlchemy model attributes
    # Without this, Pydantic only reads plain dicts — not ORM objects.
    # from_attributes=True (previously called orm_mode in Pydantic v1) enables
    # Pydantic to work directly with SQLAlchemy model instances.
    model_config = ConfigDict(from_attributes=True)


# PropertyListResponse wraps a list of properties with a count.
# Useful for the map view where the frontend needs to know total results
# for display — e.g. "Showing 24 properties"
class PropertyListResponse(BaseModel):
    total: int
    properties: list[PropertyResponse]

# PropertyUpdate is used for PATCH requests — partial updates.
# Every field is Optional — the client sends only what they want to change.
# exclude_unset=True in the repository ensures unset fields are ignored entirely.
class PropertyUpdate(BaseModel):
    title: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = None
    price: Optional[Decimal] = Field(None, gt=0)
    address: Optional[str] = Field(None, min_length=1, max_length=500)
    city: Optional[str] = Field(None, min_length=1, max_length=100)
    latitude: Optional[float] = Field(None, ge=-90, le=90)
    longitude: Optional[float] = Field(None, ge=-180, le=180)
    property_type: Optional[str] = Field(None, min_length=1, max_length=50)
    status: Optional[str] = Field(None, min_length=1, max_length=50)
 